server:
  http_port: ":8080"
  token: "supersecrettoken"
  read_time_out: 5
  write_time_out: 5

db:
  host: "localhost"
  port: "5432"
  db_name: "opp_db"
  login: "opp_user"
  password: "opp_password"
  max_pool_connections: 10

cache:
  redis_addr: "localhost:6379"

stage:
  is_dev: true
  log_file_path: ./logs.txt
  github:
    client_id: "Ov23li8vNj3ti3wXGMP8"
    redirect_uri: "https://d4d7b25d42f1.ngrok-free.app/api/auth/github/callback"
    scopes: "user:email"

    jwt:
      jwt_secret: ""

    google:
      client_id: "226527352930-9nre7c6hc00v7sp8v3647ch1m406ibr8.apps.googleusercontent.com"
      client_secret: ""
      redirect_uri: "https://e1a804c75010.ngrok-free.app/api/auth/google/callback"
      google_token_url: "https://oauth2.googleapis.com/token"
      google_grant_type: "authorization_code"
      google_auth_url_prefix: "https://accounts.google.com/o/oauth2/v2/auth?"
      scopes:
        - "email"
        - "profile"